# Generated by Django 5.0.1 on 2024-01-17 12:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devtools', '0001_initial'),
        ('ideas', '0002_remove_idea_photo_idea_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='idea',
            name='devtool',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='devtools.devtool', verbose_name='작성자'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='idea',
            name='image',
            field=models.ImageField(blank=True, upload_to='ideas/%Y%m%d', verbose_name='이미지'),
        ),
        migrations.AlterField(
            model_name='idea',
            name='interest',
            field=models.IntegerField(),
        ),
    ]
