# Generated by Django 4.2.9 on 2024-01-12 16:46

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
from django.utils import timezone

def add_initial_data(apps, schema_editor):
    print("초기 데이터 생성중.....")
    Review = apps.get_model('reviews', 'Review')
    if not Review.objects.all().exists():
        Review.objects.create(
            title='외계인',
            directors='최동훈',
            actors='김우빈, 류준열, 김태리',
            rating=3.1,
            genres='ACTION',
            running_time = 122,
            release_year = 2024,
            content='''
            인간의 몸속에 가둬진 외계인 죄수의 탈옥을 막으려다 과거에 갇혀버린 ‘이안’(김태리)은 우여곡절 끝에 시간의 문을 열 수 있는 ‘신검’을 되찾고, ‘썬더’(김우빈)를 찾아 자신이 떠나온 미래로 돌아가려고 한다. 한편 이안을 위기의 순간마다 도와주는 ‘무륵’(류준열)은 자신의 몸속에 느껴지는 이상한 존재에 혼란을 느낀다. 그런 ‘무륵’ 속에 요괴가 있다고 의심하는 삼각산 두 신선 ‘흑설’(염정아)과 ‘청운’(조우진), 소문 속 신검을 빼앗아 눈을 뜨려는 맹인 검객 ‘능파’(진선규), 신검을 차지하려는 ‘자장’(김의성)까지 ‘이안’과 ‘무륵’을 쫓기 시작한다.

            현재, 탈옥한 외계인 죄수 ‘설계자’가 폭발 시킨 외계물질 ‘하바’로 인해 수많은 사람들이 죽고, 우연히 외계인을 목격한 ‘민개인’(이하늬)은 이것이 시작에 불과함을 알게 된다. 모든 하바가 폭발하기까지 남은 시간은 단 48분, 마침내 시간의 문을 열고 무륵, 썬더, 두 신선과 함께 현재로 돌아온 이안. 외계인에 맞서 하바의 폭발을 막고 사람들을 구해야만 한다!
                    ''',
            image_url = "https://an2-img.amz.wtchn.net/image/v2/Meg4v7qe4zVlBSLWvnYGlg.jpg?jwt=ZXlKaGJHY2lPaUpJVXpJMU5pSjkuZXlKdmNIUnpJanBiSW1SZk5Ea3dlRGN3TUhFNE1DSmRMQ0p3SWpvaUwzWXlMM04wYjNKbEwybHRZV2RsTHpFM01ESTVNVGd4T1RJd09EZzFPRGt5TmpRaWZRLjlQUXhmaHdMNHBjUVNXNl9PSHduSWhqRDM1ejN2Vy1JWVdhUEhxTGtwekE",
            save_date=timezone.now(),
        )
        Review.objects.create(
            title='위시',
            directors='크리스 벅',
            actors='크리스 파인, 아리아나 드보우즈',
            rating=3.0,
            genres='COMEDY',
            running_time = 95,
            release_year = 2023,
            content='''
            "나 이렇게 소원을 빌어.
            지금보다 더 큰 꿈 꿀 수 있는 우리"

            소원이 실제로 이루어지는 마법의 왕국 ‘로사스’. 그 곳에 살고 있는 총명하고 꿈 많은 소녀 '아샤'는 마음 속 깊이 사랑하는 ‘로사스’에 도움이 되기 위해 모두의 존경을 받는 '매그니피코 왕'을 찾아갔다가 그의 숨겨진 계획을 알게 된다. 혼란에 빠진 '아샤'의 간절한 부름에 무한한 에너지를 지닌 특별한 ‘별’이 하늘에서 내려오고 귀여운 염소 친구 '발렌티노'와 함께 이들은 진심 어린 소원과 용기가 얼마나 놀라운 일들을 만들어낼 수 있는지 증명하기 위해 '매그니피코 왕'에 맞서기로 결심한다. 그러나 '매그니피코 왕'은 자신의 힘을 이용해 '아샤'와 친구들을 위협하게 되고 이들은 큰 난관에 부딪히게 되는데...        
            ''',
            image_url = "https://an2-img.amz.wtchn.net/image/v2/CdpL_1MkyE4_xJQxqg3U7Q.jpg?jwt=ZXlKaGJHY2lPaUpJVXpJMU5pSjkuZXlKdmNIUnpJanBiSW1SZk5Ea3dlRGN3TUhFNE1DSmRMQ0p3SWpvaUwzWXlMM04wYjNKbEwybHRZV2RsTHpFMk9UazVORGd5TnpNME56QXhPVEEwTVRJaWZRLndxQXRWbVFtcGVrTW9wcE41Z3ZILXR6b2lwRFZfTEVnUURKUl9oaWJvQnM",
            save_date=timezone.now(),
        )
        Review.objects.create(
            title='노량: 죽음의 바다',
            directors='김한민',
            actors='김윤석, 백윤식, 정재영',
            rating=3.2,
            genres='ACTION',
            running_time = 152,
            release_year = 2023,
            content='''
            임진왜란 발발로부터 7년이 지난 1598년 12월. 이순신(김윤석)은 왜군의 수장이던 도요토미 히데요시가 갑작스럽게 사망한 뒤 왜군들이 조선에서 황급히 퇴각하려 한다는 것을 알게 된다. 

            “절대 이렇게 전쟁을 끝내서는 안 된다” 

            왜군을 완벽하게 섬멸하는 것이 이 전쟁을 올바르게 끝나는 것이라 생각한 이순신은 명나라와 조명연합함대를 꾸려 왜군의 퇴각로를 막고 적들을 섬멸하기로 결심한다. 하지만 왜군의 뇌물 공세에 넘어간 명나라 도독 진린(정재영)은 왜군에게 퇴로를 열어주려 하고, 설상가상으로 왜군 수장인 시마즈(백윤식)의 살마군까지 왜군의 퇴각을 돕기 위해 노량으로 향하는데…

            2023년 12월, 모두를 압도할 최후의 전투가 시작된다!        
            ''',
            image_url = "https://an2-img.amz.wtchn.net/image/v2/wTNkUETl-lMkhzhgWqHeEw.jpg?jwt=ZXlKaGJHY2lPaUpJVXpJMU5pSjkuZXlKdmNIUnpJanBiSW1SZk5Ea3dlRGN3TUhFNE1DSmRMQ0p3SWpvaUwzWXlMM04wYjNKbEwybHRZV2RsTHpFM01ESTRNek0xTVRnME5UWXdOalE0TkRRaWZRLmJCRzRLNWgxaktDSXFqREhUa1BOUW1aRUdqU3hHMWxzVUstUnJrbzRGVmM",
            save_date=timezone.now(),
        )
        Review.objects.create(
            title='어바웃 타임',
            directors='리처드 커티스',
            actors='도널 글리슨, 레이첼 맥아담스',
            rating=4.3,
            genres='',
            running_time = 123,
            release_year = 2013,
            content='''
            모태솔로 팀(도널 글리슨)은 성인이 된 날, 아버지(빌 나이)로부터 놀랄만한 가문의 비밀을 듣게 된다. 바로 시간을 되돌릴 수 있는 능력이 있다는 것! 그것이 비록 히틀러를 죽이거나 여신과 뜨거운 사랑을 할 수 는 없지만, 여자친구는 만들어 줄 순 있으리...

            꿈을 위해 런던으로 간 팀은 우연히 만난 사랑스러운 여인 메리에게 첫눈에 반하게 된다. 그녀의 사랑을 얻기 위해 자신의 특별한 능력을 마음껏 발휘하는 팀. 어설픈 대시, 어색한 웃음은 리와인드! 뜨거웠던 밤은 더욱 뜨겁게 리플레이! 꿈에 그리던 그녀와 매일매일 최고의 순간을 보낸다.

            하지만 그와 그녀의 사랑이 완전해 질수록 팀을 둘러싼 주변 상황들은 미묘하게 엇갈리고, 예상치 못한 사건들이 여기저기 나타나기 시작하는데…

            어떠한 순간을 다시 살게 된다면,
            과연 완벽한 사랑을 이룰 수 있을까?           
                    ''',
            image_url = "https://an2-img.amz.wtchn.net/image/v2/jENE7VlqUpBKBIfpyHRing.jpg?jwt=ZXlKaGJHY2lPaUpJVXpJMU5pSjkuZXlKdmNIUnpJanBiSW1SZk5Ea3dlRGN3TUhFNE1DSmRMQ0p3SWpvaUwzWXhMMmt3WjNsdlpEbDFlRzFwZUdrNVltUjZhV2xySW4wLjRjRFByUGhqQUt2c2tsdndzWmRmUmM2bjlYbGc1OWJaaWhXWXJmaEdMeWc",
            save_date=timezone.now(),
        )
        print("생성 완료!")        



class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('directors', models.CharField(max_length=100)),
                ('actors', models.CharField(max_length=100)),
                ('release_year', models.IntegerField(validators=[django.core.validators.MinValueValidator(1000), django.core.validators.MaxValueValidator(2024)])),
                ('genres', models.CharField(choices=[('액션', 'Action'), ('코미디', 'Comedy'), ('드라마', 'Drama'), ('로맨스', 'Romance'), ('스릴러', 'Thriller')], max_length=20)),
                ('rating', models.DecimalField(decimal_places=1, max_digits=2, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(5.0)])),
                ('running_time', models.IntegerField()),
                ('content', models.TextField()),
                ('save_date', models.DateTimeField(blank=True, null=True)),
                ('image_url', models.TextField(blank=True, null=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RunPython(add_initial_data),
    ]
